services:
  debian10-mirror:
    build: ./debian-10
    container_name: debian10-mirror
    ports:
      - "8083:80"
    volumes:
      - debian10_data:/var/www/html/debian-10
  debian11-mirror:
    build: ./debian-11
    container_name: debian11-mirror
    ports:
      - "8084:80"
    volumes:
      - debian11_data:/var/www/html/debian-11

volumes:
  debian10_data:
