version: '3.8'

services:
  ubuntu-mirror:
    build: ./mirror-sync
    container_name: ubuntu-mirror
    environment:
      - MIRROR_NAME=ubuntu
      - MIRROR_DIR=/var/www/html
      - UPSTREAM=rsync://ubuntu.ethz.ch/ubuntu/
    volumes:
      - /mirrordata/ubuntu:/var/www/html
    restart: unless-stopped
    ports:
      - "18082:80"

  debian-mirror:
    build: ./mirror-sync
    container_name: debian-mirror
    environment:
      - MIRROR_NAME=debian
      - MIRROR_DIR=/var/www/html
      - UPSTREAM=rsync://ubuntu.ethz.ch/debian/
    volumes:
      - /mirrordata/debian:/var/www/html
    restart: unless-stopped
    ports:
      - "18083:80"
    
  centos-mirror:
    build: ./mirror-sync
    container_name: centos-mirror
    environment:
      - MIRROR_NAME=centos
      - MIRROR_DIR=/var/www/html
    volumes:
      - /mirrordata/centos:/var/www/html
    restart: unless-stopped
    ports:
      - "18084:80"
  
  rocky-mirror:
    build: ./mirror-sync
    container_name: rocky-mirror
    environment:
      - MIRROR_NAME=rocky
      - MIRROR_DIR=/var/www/html
    volumes:
      - /mirrordata/rocky:/var/www/html
    restart: unless-stopped
    ports:
      - "18085:80"

