version: '3'

services:
  arch-mirror:
    build: ./arch
    container_name: arch-mirror
    ports:
      - "8081:80"
    volumes:
      - arch_data:/var/www/html/arch

  ubuntu-mirror:
    build: ./ubuntu
    container_name: ubuntu-mirror
    ports:
      - "8082:80"
    volumes:
      - ubuntu_data:/var/www/html/ubuntu

  debian-mirror:
    build: ./debian
    container_name: debian-mirror
    ports:
      - "8083:80"
    volumes:
      - debian_data:/var/www/html/debian

  centos-mirror:
    build: ./centos
    container_name: centos-mirror
    ports:
      - "8084:80"
    volumes:
      - centos_data:/var/www/html/centos
  rocky-mirror:
    build: ./rocky
    container_name: rocky-mirror
    ports:
      - "8085:80"
    volumes:
      - rocky_data:/var/www/html/rocky


volumes:
  arch_data:
  ubuntu_data:
  debian_data:
  centos_data:
  rocky_data:
